version: '3'
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    restart: always
    volumes:
      - ${WEB_ROOT}:/var/www/html/:rw
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/sites/:/etc/nginx/sites/:ro
      - ./nginx/logs:/var/log/nginx/:rw
    links:
      - php7:php7
    environment:
      SET_CONTAINER_TIMEZONE: "TRUE"
      CONTAINER_TIMEZONE: "Asia/Shanghai"
  php7:
    build:
      context: ./php7
    ports:
      - "${PHP_FPM_PORT}:9000"
    container_name: php7
    restart: always
    links:
      - mysql:mysql
      - redis:redis
    volumes:
      - ${WEB_ROOT}:/var/www/html/:rw
      - ./php7/logs:/var/log/php:rw
    extra_hosts:
      - ${PHP_FPM_EXTRA_HOSTS}
    environment:
      SET_CONTAINER_TIMEZONE: "TRUE"
      CONTAINER_TIMEZONE: "Asia/Shanghai"
  mysql:
    build:
      context: ./mysql
    ports:
      - "${MYSQL_PORT}:3306"
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      SET_CONTAINER_TIMEZONE: "TRUE"
      CONTAINER_TIMEZONE: "Asia/Shanghai"
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf:ro
      - ${DATA_PATH}:/var/lib/mysql/:rw
      - ./mysql/logs/:/var/log/mysql/:rw
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
