version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    restart: always
    volumes:
      - webroot:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/sites/:/etc/nginx/sites/:ro
      - ./nginx/logs:/var/log/nginx/:rw
    networks:
      - webnet
    environment:
      TZ: ${TZ}
  php7:
    build:
      context: ./php7
    container_name: php7
    restart: always
    volumes:
      - webroot:/var/www/html/:rw
      - ./php7/logs:/var/log/php:rw
    extra_hosts:
      - ${PHP_FPM_EXTRA_HOSTS}
    networks:
      - webnet
    environment:
      TZ: ${TZ}
  mysql:
    build:
      context: ./mysql
    ports:
      - "${MYSQL_PORT}:3306"
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      SET_CONTAINER_TIMEZONE: "TRUE"
      CONTAINER_TIMEZONE: "Asia/Shanghai"
    networks:
      - webnet
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf:ro
      - ${DATA_PATH}:/var/lib/mysql/:rw
      - ./mysql/logs/:/var/log/mysql/:rw
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - webnet
    ports:
      - "${REDIS_PORT}:6379"
  nodejs:
    build:
      context: ./nodejs
    restart: always
    volumes:
      - webroot:/app
networks:
  webnet:
volumes:
  webroot:
    driver: local
    driver_opts:
      type: none
      device: ${WEB_ROOT}
      o: bind